config/routes.rb
Cccash2::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions" }

  resources :users
  resources :workshifts
  resources :cashboxes
  resources :printers
  resources :groups
  resources :transactions

  resources :workshifts do
    member do
      put   :toggle_activation
      post  :clear
      get   :billing
    end
  end

  resources :special_guests do
    collection do
      get 'search'
      get 'admin_search'
    end
  end

  resource :cart do
    member do
      put     'add_ticket_to'
      delete  'remove_ticket_from'
      get     'checkout'
      post    'wait_for_cashbox'
      get     'cancel_most_recent'
      post    'confirm_cancel'
      get     'open_cashbox'
    end
  end

  resources :tickets do
    collection do
      post 'sort'
    end
  end

  match "admin"       => "admin#index"
  match "statistics"  => "statistics#index"
  match "tasks"       => "tasks#index"

  if Rails.env != 'production'
    %w(open status wait_for_close print).each do |command|
      match "/#{command}" => "mock_cashbox##{command}"
    end
  end

  root :to => 'admin#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  
  has_many :special_guests
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new params[:group]
  end

  def create
    @group = Group.new params[:group]

    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

    if @group.update_attributes(params[:group])
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    group = Group.find(params[:id])

    group.destroy if group

    redirect_to groups_path
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group_form.html.erb
<%= error_messages_for @group %>

<%= form_for @group do |f| %>
  <table>
    <tr>
      <th>Name</th>
      <th><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit %></td>
    </tr>
<% end %>

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Groups#destroy</h1>
<p>Find me in app/views/groups/destroy.html.erb</p>

app/views/groups/edit.html.erb
<%= render :partial => 'group_form' %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<p>
  <%= link_to "Create new group", new_group_path %>
</p>

<table>
  <% @groups.each do |group| %>
  <tr>
    <td>
      <%= group.name %>
    </td>
    <td>
      <%= link_to "edit", edit_group_path(group) %>
      <%= link_to "delete", group_path(group), :method => :delete, :confirm => "Sure?" %>
    </td>
  </tr>
  <% end %>
</table>

app/views/groups/new.html.erb
<%= render :partial => 'group_form' %>

app/views/groups/show.html.erb
<h1>Groups#show</h1>
<p>Find me in app/views/groups/show.html.erb</p>

app/views/groups/update.html.erb
<h1>Groups#update</h1>
<p>Find me in app/views/groups/update.html.erb</p>