config/routes.rb
Cccash2::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions" }

  resources :users
  resources :workshifts
  resources :cashboxes
  resources :printers
  resources :groups
  resources :transactions

  resources :workshifts do
    member do
      put   :toggle_activation
      post  :clear
      get   :billing
    end
  end

  resources :special_guests do
    collection do
      get 'search'
      get 'admin_search'
    end
  end

  resource :cart do
    member do
      put     'add_ticket_to'
      delete  'remove_ticket_from'
      get     'checkout'
      post    'wait_for_cashbox'
      get     'cancel_most_recent'
      post    'confirm_cancel'
      get     'open_cashbox'
    end
  end

  resources :tickets do
    collection do
      post 'sort'
    end
  end

  match "admin"       => "admin#index"
  match "statistics"  => "statistics#index"
  match "tasks"       => "tasks#index"

  if Rails.env != 'production'
    %w(open status wait_for_close print).each do |command|
      match "/#{command}" => "mock_cashbox##{command}"
    end
  end

  root :to => 'admin#index'

end

app/views/shared/_admin_menu.html.erb
<%= link_to "Logout",         destroy_user_session_path, :method => :delete %> |
<%= link_to "Overview",       admin_path %> |
<%= link_to "Users",          users_path %> |
<%= link_to "Groups",         groups_path %> |
<%= link_to "Workshifts",     workshifts_path %> |
<%= link_to "Transactions",   transactions_path %> |
<%= link_to "Special Guests", special_guests_path %> |
<%= link_to "Tickets",        tickets_path %> |
<%= link_to "Statistics",     'statistics#index' %>

app/views/shared/_login_menu.html.erb
<%# link_to "Login", new_session_path %>

app/views/shared/_notice.html.erb
<div id="notice" style="display: none">
  <%= flash[:notice] %>
  <%= flash[:alert] %>
</div>

<%= flash_js_tag %>

app/views/shared/_user_menu.html.erb
User
<%= link_to "Logout",   destroy_user_session_path, :method => :delete %> |
<%= link_to "Tickets",  cart_path %> |
<%= link_to "Storno",   cancel_most_recent_cart_path %> |
<%= link_to "Tasks",    :controller => "tasks", :action => "index" %>