config/routes.rb
Cccash2::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions" }

  resources :users
  resources :workshifts
  resources :cashboxes
  resources :printers
  resources :groups
  resources :transactions

  resources :workshifts do
    member do
      put   :toggle_activation
      post  :clear
      get   :billing
    end
  end

  resources :special_guests do
    collection do
      get 'search'
      get 'admin_search'
    end
  end

  resource :cart do
    member do
      put     'add_ticket_to'
      delete  'remove_ticket_from'
      get     'checkout'
      post    'wait_for_cashbox'
      get     'cancel_most_recent'
      post    'confirm_cancel'
      get     'open_cashbox'
    end
  end

  resources :tickets do
    collection do
      post 'sort'
    end
  end

  match "admin"       => "admin#index"
  match "statistics"  => "statistics#index"
  match "tasks"       => "tasks#index"

  if Rails.env != 'production'
    %w(open status wait_for_close print).each do |command|
      match "/#{command}" => "mock_cashbox##{command}"
    end
  end

  root :to => 'admin#index'

end

app/models/workshift.rb
class Workshift < ActiveRecord::Base
  include AASM
  aasm_column :state

  has_many    :transactions
  has_many    :workshift_tickets
  belongs_to  :cashbox
  belongs_to  :user
  belongs_to  :cleared_by,
              :class_name  => 'User'

  accepts_nested_attributes_for :workshift_tickets

  validates_presence_of       :user,  :cashbox, :money
  validates_numericality_of   :money, :greater_than => 0
  validate                    :no_busy_angel,         :on => :create
  validate                    :must_have_tickets,     :on => :create
  validate                    :cashbox_availability,  :on => :create

  scope :in_progress, where("state != 'cleared'").order("created_at ASC")
  scope :cleared,     where("state = 'cleared'").order("created_at ASC")

  aasm_initial_state :inactive

  aasm_state :inactive
  aasm_state :waiting_for_login
  aasm_state :active,   :enter => :set_started_at, :exit => :set_ended_at
  aasm_state :standby
  aasm_state :cleared,  :enter => :set_cleared_at

  aasm_event :activate do
    transitions :from => :inactive,
                :to   => :waiting_for_login
  end

  aasm_event :deactivate do
    transitions :from => :active,
                :to   => :inactive

    transitions :from => :waiting_for_login,
                :to   => :inactive

    transitions :from => :standby,
                :to   => :inactive
  end

  aasm_event :login do
    transitions :from => :waiting_for_login,
                :to   => :active

    transitions :from => :standby,
                :to   => :active

    transitions :from => :active,
                :to   => :active
  end

  aasm_event :logout do
    transitions :from => :active,
                :to   => :standby
  end

  aasm_event :clear do
    transitions :from => :inactive,
                :to   => :cleared
  end

  def set_started_at
    update_attributes! :started_at => Time.now unless started_at
  end

  def set_ended_at
    update_attributes! :ended_at => Time.now
  end

  def set_cleared_at
    update_attributes! :cleared_at => Time.now
  end

  def status
    state.humanize
  end

  def event_possible? requested_event
    aasm_events_for_current_state.include? requested_event
  end

  def toggle_activation
    if aasm_events_for_current_state.include?(:activate)
      activate!
    elsif aasm_events_for_current_state.include?(:deactivate)
      deactivate!
    end
  end

  def start!
    self.update_attributes(:started_at => Time.now)
  end

  def end!
    self.update_attributes(:ended_at => Time.now)
  end

  def grouped_tickets_count
    stats = {}
    transactions.each do |tr|
      tr.tickets.flatten.each do |tick|

        workshift_ticketss = workshift_tickets.first(
          :conditions => { :ticket_id => tick.id }
        ).try(:amount)

        stats[tick.id] ||= {}
        stats[tick.id][:ticket] ||= tick
        stats[tick.id][:total] ||= 0
        stats[tick.id][:canceled] ||= 0
        stats[tick.id][:valid] ||= 0
        stats[tick.id][(tr.canceled? ? :canceled : :valid)] += 1
        stats[tick.id][:total] += 1
        stats[tick.id][:workshift_tickets] = workshift_ticketss || 0
      end
    end
    stats
  end

  def workshift_tickets_for ticket_id
    workshift_tickets.find_by_ticket_id(ticket_id).try(:amount) || 0
  end

  def self.count_by_state
    {'active'             => 0,
     'waiting_for_login'  => 0,
     'inactive'           => 0,
     'standby'            => 0,
     'cleared'            => 0}.merge(self.count(:group => :state))
  end

  private
  def no_busy_angel
    errors.add(:base, "The user you chose is busy") if user && user.workshift
  end

  def must_have_tickets
    ticket_amount = workshift_tickets.inject(0) do |memo, wt|
      memo += wt.amount || 0
    end

    if ticket_amount == 0
      errors.add(:base, "You have not supplied any tickets")
    end
  end

  def cashbox_availability
    if Cashbox.busy.include? self.cashbox
      errors.add(:base, "Cashbox is already in use by other Workshift")
    end
  end
end

app/controllers/workshifts_controller.rb
class WorkshiftsController < ApplicationController
  def index
    @active_workshifts    = Workshift.in_progress.all
    @inactive_workshifts  = Workshift.cleared.all
  end

  def new
    @workshift = Workshift.new params[:workshift]
  end

  def create
    @workshift = Workshift.new params[:workshift]
    if @workshift.save
      redirect_to admin_path
    else
      render :new
    end
  end

  def show
    @workshift    = Workshift.find params[:id]
    @transactions = Transaction.paginate(
      :page       => params[:page],
      :per_page   => 15,
      :conditions => {:workshift_id => @workshift.id},
      :order      => "created_at desc"
    )
  end

  def billing
    @workshift = Workshift.find params[:id]
  end

  def edit
    @workshift = Workshift.find params[:id]
  end

  def update
    @workshift = Workshift.find params[:id]

    if @workshift.update_attributes( params[:workshift] )
      redirect_to admin_path
    else
      render :edit
    end
  end

  def destroy
    workshift = Workshift.find params[:id]

    workshift.destroy if workshift

    redirect_to admin_path
  end

  def toggle_activation
    workshift   = Workshift.find params[:id]

    respond_to do |format|
      format.js do
        if workshift.toggle_activation
          @workshifts = Workshift.in_progress
          @workshift_count = Workshift.count_by_state
          render :update do |page|
            page['workshifts'].replace(render(:partial => 'workshift_overview'))
          end
        else
          render :nothing => true
        end
      end
    end
  end

  def clear
    @workshift = Workshift.find params[:id]

    @workshift.transaction do
      @workshift.clear!
      @workshift.update_attributes! :cleared_by_id => current_user.id
      if params[:taint_user]
        @workshift.user.update_attributes! :tainted => true;
      end
    end

    redirect_to admin_path
  end

end

app/helpers/workshifts_helper.rb
module WorkshiftsHelper
  
  def cashboxes_for_select
    available = Cashbox.all - Workshift.active.map {|ws| ws.cashbox}
    available.map {|cb| [cb.name, cb.id]}
  end
  
  def users_for_select
    available = User.angels - User.busy.angels
    available.map do |a|
      if a.tainted?
        ["#{a.login} (tainted!)", a.id]
      else
        [a.login, a.id]
      end
    end 
  end
  
end

app/views/workshifts/_workshift.html.erb
<tr class="<%= cycle('even', 'uneven')%>">
  <td><%= workshift.id %></td>
  <td><%= workshift.cashbox.name %></td>
  <td><%= link_to(workshift.user.login, edit_user_path(workshift.user)) %></td>
  <td class="right"><%= nice_price(workshift.money) %></td>
  <td><strong><%= workshift.status %></strong></td>
  <td><strong>
    <% if workshift.cleared? %>
      <%= link_to_user(workshift.cleared_by) %>
    <% end %>
  </strong></td>
  <td>
    <%= link_to 'Transactions', workshift_path(workshift) %>
  </td>
</tr>

app/views/workshifts/_workshift_form.html.erb
<%= error_messages_for @workshift %>

<%= form_for @workshift do |f| %>
  <table>
    <tr>
      <td>Cashbox</td>
      <td><%= f.select :cashbox_id, cashboxes_for_select %></td>
    </tr>
    <tr>
      <td>User</td>
      <td><%= f.select :user_id, users_for_select %></td>
    </tr>
    <tr>
      <td>Money</td>
      <td><%= f.text_field :money %></td>
    </tr>
    <tr>
      <td colspan="2">
        <h4>Tickets in Cashbox</h4>
        <table>
          <% Ticket.standard.each do |ticket| %>
          <tr>
            <td><%= ticket.name %></td>
            <td>
              <%= text_field_tag "workshift[workshift_tickets_attributes][][amount]", 0 %>
              <%= hidden_field_tag "workshift[workshift_tickets_attributes][][ticket_id]", ticket.id %>
            </td>
          </tr>
          <% end %>
        </table>
      </td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit %></td>
    </tr>
  </table>
<% end %>

app/views/workshifts/_workshift_list.html.erb
<div id="workshifts">
  <table>
    <tr>
      <th>ID</th>
      <th>Cashbox</th>
      <th>Angel</th>
      <th>Money</th>
      <th>Status</th>
			<th>Cleared by</th>
			<th>Actions</th>
    </tr>
    <% @workshifts.each do |workshift| %>
    <tr class="<%= cycle('even', 'uneven')%>">
      <td><%= workshift.id %></td>
      <td><%= workshift.cashbox.name %></td>
      <td><%= link_to(workshift.user.login, edit_user_path(workshift.user)) %></td>
      <td class="right"><%= nice_price(workshift.money) %></td>
      <td><strong><%= workshift.status %></strong></td>
      <td><strong>
				<% if workshift.cleared? %>
				  <%= link_to_user(workshift.cleared_by) %>
        <% end %>
			</strong></td>
			<td>
      	<%= link_to 'Transactions', workshift_path(workshift) %>
    	</td>
		</tr>
    <% end %>
  </table>
</div>

app/views/workshifts/_workshift_overview.html.erb
<div id="workshifts">
  <h1>Workshifts
    <span class='badge state_active'><%= @workshift_count['active'] %> active</span>
    <span class='badge state_waiting_for_login'><%= @workshift_count['waiting_for_login'] + @workshift_count['standby'] %> waiting</span>
    <span class='badge state_inactive'><%= @workshift_count['inactive'] %> inactive</span>
    <span class='badge state_cleared'><%= @workshift_count['cleared'] %> cleared</span></h1>

  <p><%= link_to "Create new Workshift", new_workshift_path %></p>
  
  <table>
    <tr>
      <th>ID</th>
      <th>Cashbox</th>
      <th>Angel</th>
      <th>Money</th>
      <th>Status</th>
      <th colspan='5'>Actions</th>
    </tr>
    <% @workshifts.group_by(&:status).each do |status, workshifts| %>
    <% workshifts.each do |workshift| %>
      <tr class="<%= cycle('even', 'uneven')%>">
      <td><%= workshift.id %></td>
      <td><%= workshift.cashbox.name %></td>
      <td><%= link_to_user(workshift.user) %></td>
      <td class="right"><%= nice_price(workshift.money) %></td>
      <td class='<%= "state_#{workshift.state}" %>'><strong><%= status %></strong></td>
      <td id="activate_workshift_<%= workshift.id -%>">
        <%= toggle_activation_link workshift %>
      </td>
      <td>
        <% if workshift.transactions.empty? %>
          <%= link_to 'Delete', workshift_path(workshift), :method => :delete, :confirm => "Are you sure?" %>
        <% end %>
      </td>

      <td><%= link_to 'Billing', billing_workshift_path(workshift) %></td>
      <td><%= link_to 'Details', workshift_path(workshift) %></td>
      <td><%= link_to 'edit', edit_workshift_path(workshift) %></td>
      </td>
    </tr>
    <% end %>
    <% end %>
  </table>
</div>

app/views/workshifts/billing.html.erb
<h1>Chaos Computer Club Veranstaltungsgesellschaft mbH</h1>
<h3>Chaos Communication Congress <%= Time.now.year %></h3>
<h3>Kassenabrechnung:</h3>
<ul id="kassenabrechnung">
  <li>Kasse: <%= @workshift.cashbox.name %> [Schicht: <%= @workshift.id  %>]</li>
  <li>Zeitraum: <%= @workshift.started_at.to_s(:db) if @workshift.started_at %> Uhr bis: <%= @workshift.ended_at.to_s(:db) if @workshift.ended_at %> Uhr (Berlin)</li>
  <li>Kassierer/in: <%= @workshift.user.name %></li>
</ul>

<table>
    <tr>
        <th>ID</th>
        <th>Ticket Typ</th>
        <th>Preis</th>
        <th>Verkauft ( -storniert )</th>
        <th>Retour</th>
        <th>Summe</th>
    </tr>
    <% total = 0 %>
    <% @workshift.grouped_tickets_count.each do |id, stat| %>
        <tr class="<%= cycle('even', 'uneven')%>">
            <% sub_total = (stat[:valid] * stat[:ticket].price) %>
            <% total += sub_total %>
            <td><%= id %></td>
            <td><%= stat[:ticket].name %></td>
            <td class="right"><%= nice_price(stat[:ticket].price) %></td>
            <td class="centered">
              <%= stat[:total] %>
              <% if stat[:canceled] > 0 %>
                ( -<%= stat[:canceled] -%> )
              <% end %>
            </td>
            <td><%= stat[:workshift_tickets] - stat[:total] + stat[:canceled]  %></td>
            <td class="right"><%= nice_price(sub_total) %></td>
        </tr>
        <% end %>
        <tr class="bargeld">
            <td>Bargeld:</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="right"><%= nice_price(@workshift.money) %></td>
        </tr>
        <tr class="ticket-sum">
            <td>Betrag:</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="right"><%= nice_price(total + @workshift.money.to_i) %></td>
        </tr>
        <tr class="ticket-total">
            <td>Einnahmen:</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="right"><%= nice_price(total) %></td>
        </tr>
</table>

<% if @workshift.inactive? %>
    <%= form_tag clear_workshift_path(:id => @workshift.id), :class => 'hideForPrint' do %>
      <%= submit_tag 'Ist alles OK', :confirm => 'Really mark as cleared?' %>
      <% if @workshift.user.tainted? %>
        <strong>This user is tainted.</strong>
      <% else %>
        Taint this user: <%= check_box_tag 'taint_user' %>
      <% end %>
    <% end %>
<% end %>

<div id="kassierer">
  <legend>Unterschrift Kassierer</legend>
</div>

<div id="schichtleiter">
  <legend>Unterschrift Schichtleiter</legend>
</div>

app/views/workshifts/create.html.erb
<h1>Workshifts#create</h1>
<p>Find me in app/views/workshifts/create.html.erb</p>

app/views/workshifts/destroy.html.erb
<h1>Workshifts#destroy</h1>
<p>Find me in app/views/workshifts/destroy.html.erb</p>

app/views/workshifts/edit.html.erb
<h1>Workshifts#edit</h1>
<p>Here you can add more tickets to the running workshift. Please make sure twice you <i>add</i> the amount, i.e. if there are 100 Standard tickets already present and and 20 are added you must fill in <b>120</b> down there</p>
<p><%= error_messages_for @workshift %></p>

<%= form_for @workshift do |f| %>
  <table>
    <tr>
      <td>Cashbox</td>
      <td><%= @workshift.cashbox.name %></td>
    </tr>
    <tr>
      <td>User</td>
      <td><%= @workshift.user.login %></td>
    </tr>
    <tr>
      <td>Money</td>
      <td><%= @workshift.money %></td>
    </tr>
    <tr>
      <td colspan="2">
        <h4>Tickets in Cashbox</h4>
        <table>
          <% Ticket.available.each do |ticket| %>
          <tr>
            <td><%= ticket.name %></td>
            <td>
              <%= hidden_field_tag(
                    "workshift[workshift_tickets_attributes][][id]",
                    @workshift.workshift_tickets.find_by_ticket_id(ticket.id).id
              ) %>
              <%= text_field_tag(
                    "workshift[workshift_tickets_attributes][][amount]",
                    @workshift.workshift_tickets_for(ticket.id)
              ) %>
              <%= hidden_field_tag(
                    "workshift[workshift_tickets_attributes][][ticket_id]",
                    ticket.id
              ) %>
            </td>
          </tr>
          <% end %>
        </table>
      </td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit %></td>
    </tr>
  </table>
<% end %>

app/views/workshifts/index.html.erb
<h1>Active Workshifts</h1>

<div id="workshifts">
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Cashbox</th>
        <th>Angel</th>
        <th>Money</th>
        <th>Status</th>
        <th>Cleared by</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= render :partial => @active_workshifts %>
    </tbody>
  </table>
</div>



<h1>Cleared Workshifts</h1>

<div id="workshifts">
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Cashbox</th>
        <th>Angel</th>
        <th>Money</th>
        <th>Status</th>
        <th>Cleared by</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= render :partial => @inactive_workshifts %>
    </tbody>
  </table>
</div>

app/views/workshifts/new.html.erb
<h1>New Workshift</h1>

<%= render :partial => "workshift_form" %>

app/views/workshifts/show.html.erb
<h1>Workshift Details</h1>

<table>
  <tr>
    <td>Angel:</td>
    <td><%= @workshift.user.login %> (<%= @workshift.user.name %>)</td>
  </tr>
  <tr>
    <td>Money</td>
    <td><%= nice_price @workshift.money %></td>
  </tr>
  <tr>
    <td>Started:</td>
    <td><%= @workshift.started_at.timestamp if @workshift.started_at %></td>
  </tr>
  <tr>
    <td>Ended:</td>
    <td><%= @workshift.ended_at.timestamp if @workshift.ended_at %></td>
  </tr>
  <tr>
    <td>Transactions:</td>
    <td><%= @workshift.transactions.count %></td>
  </tr>
  <tr>
    <td>State</td>
    <td><%= @workshift.status %></td>
  </tr>
  <% if @workshift.cleared? %>
  <tr>
    <td>Cleared:</td>
    <td>
      <%= @workshift.cleared_at.timestamp if @workshift.cleared %>
    </td>
  </tr>
  <tr>
    <td>Cleared by:</td>
    <td><%= link_to(@workshift.cleared_by.login, user_path(@workshift.cleared_by)) %></td>
  </tr>
  <% end %>
</table>


<h1>Transactions</h1>

<p><%= will_paginate @transactions %></p>

<table class="overview">
  <thead>
    <tr>
      <th>ID</th>
      <th>Workshift</th>
      <th>Angel</th>
      <th>Time</th>
      <th>Valid</th>
      <th>Tickets</th>
      <th class="total">Total</th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => @transactions %>
  </tbody>
</table>

<p><%= will_paginate @transactions %></p>

app/views/workshifts/update.html.erb
<h1>Workshifts#update</h1>
<p>Find me in app/views/workshifts/update.html.erb</p>