config/routes.rb
Cccash2::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions" }

  resources :users
  resources :workshifts
  resources :cashboxes
  resources :printers
  resources :groups
  resources :transactions

  resources :workshifts do
    member do
      put   :toggle_activation
      post  :clear
      get   :billing
    end
  end

  resources :special_guests do
    collection do
      get 'search'
      get 'admin_search'
    end
  end

  resource :cart do
    member do
      put     'add_ticket_to'
      delete  'remove_ticket_from'
      get     'checkout'
      post    'wait_for_cashbox'
      get     'cancel_most_recent'
      post    'confirm_cancel'
      get     'open_cashbox'
    end
  end

  resources :tickets do
    collection do
      post 'sort'
    end
  end

  match "admin"       => "admin#index"
  match "statistics"  => "statistics#index"
  match "tasks"       => "tasks#index"

  if Rails.env != 'production'
    %w(open status wait_for_close print).each do |command|
      match "/#{command}" => "mock_cashbox##{command}"
    end
  end

  root :to => 'admin#index'

end

app/models/cart.rb
class Cart
  
  attr_accessor :tickets, :special_guest_id
  
  def initialize
    @tickets          = []
    @special_guest_id = nil
  end
  
  def add ticket
    @tickets ||= []
    
    if ticket.custom? && 0 < custom_tickets.size
      false
    else
      @tickets << ticket
    end
  end
  
  def custom_tickets
    @tickets.select { |ticket| ticket.custom }
  end
  
  def remove position
    @tickets.delete_at position
  end
  
  def reset
    @special_guest_id = nil
    @tickets = []
  end
  
  def total_price
    @tickets.inject(0) { |sum, ticket| sum + ticket.price }
  end
  
  def create_transaction options
    transaction = Transaction.new(
      options.merge(:special_guest_id => @special_guest_id)
    )
    
    @tickets.each do |ticket|
      transaction.tickets << ticket
    end
    
    transaction.save
    transaction
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  skip_before_filter  :admin_status_required

  before_filter       :get_cart, :get_cashbox
  before_filter       :check_workshift_and_ip
  before_filter       :check_valid_session, :only => :checkout

  def show
    @cart.reset
    session[:valid] = true
  end

  def add_ticket_to
    ticket = Ticket.find(params[:id])

    if params[:special_guest_id]
      @cart.special_guest_id = params[:special_guest_id]
    end

    render :update do |page|
      unless @cart.add( ticket )
        flash[:notice] = "Cannot add another custom ticket"
        page[:notice].replace :partial => 'shared/notice'
      end

      flash[:notice] = nil
      page[:cart].replace render(:partial => 'cart')
    end
  end

  def remove_ticket_from
    @cart.remove params[:position].to_i

    render :update do |page|
      page[:cart].replace render(:partial => 'cart')
    end
  end

  # The cart object tries to create a valid transaction from the given tickets
  # and workshift. If the resulting transaction is valid the regular checkout
  # template is rendered. If not it redirects back to the cart to start over.
  def checkout
    session[:valid] = false

    #begin
      Transaction.transaction do
        @transaction = @cart.create_transaction(:workshift => current_user.workshift)
        if @transaction.errors.empty?
          @cashbox.open_drawer
          if !@transaction.presale then
            @bons = @transaction.print_bon!
          end

          render
          @cart.reset
        else
          flash[:notice] = "Invalid Transaction: #{transaction_errors}"
          redirect_to cart_path
        end
      end
    #rescue => e
    #  puts ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    #  puts e.message
    #  flash[:notice] = "( #{e.class} ) - #{e.message}\n" \
    #                   "Last Transaction will be canceled"
    #  redirect_to cart_path
    #  return
    #end
  end

  def open_cashbox
    @cashbox.open_drawer
    flash[:notice] = "Opened cashbox"
    redirect_to cart_path
  end

  def cancel_most_recent
    @last_transaction = current_user.workshift.transactions.last

    unless @last_transaction && !@last_transaction.canceled?
      flash[:notice] = "Could not cancel transcation"
      redirect_to cart_path
    end
  end

  def confirm_cancel
    supervisor = User.where(:login => params[:login]).first

    if supervisor && supervisor.valid_password?(params[:password]) && supervisor.admin?
      @last_transaction = Transaction.find(params[:transaction_id])
      @last_transaction.cancel if @last_transaction
      @cashbox.open_drawer
    else
      flash[:notice] = "Invalid Admin Account"
      redirect_to cart_path
    end
  end

  def wait_for_cashbox
    respond_to do |format|
      format.js do
        if @cashbox.wait_for_closed_drawer
          render :update do |page|
            page.redirect_to cart_path
          end
        else
          render :nothing => true
        end
      end
    end
  end


  private

    def get_cart
      @cart = ( session[:cart] ||= Cart.new )
    end

    def get_cashbox
      if current_user && current_user.workshift
        @cashbox = current_user.workshift.cashbox
      end
    end


    def check_valid_session
      if session[:valid] == false
        flash[:notice] = "Exessive Checkout Error - Calm down or fix your mouse"
        redirect_to cart_path
      end
    end

    def transaction_errors
      errors = []
      @transaction.errors.each do |field, error|
        errors << error
      end
      errors.join(",")
    end

end

app/helpers/cart_helper.rb
module CartHelper
  def wait_for_close_with_button(action=nil)
    javascript_tag(
      remote_function( :url => wait_for_cashbox_cart_path )
    )
  end
end

app/views/carts/_cart.html.erb
<div id="cart">
  <h1>Cart</h1>
  <table>
    <tr>
      <th>Ticket</th>
      <th>Price</th>
      <th>Action</th>
    </tr>
    <% @cart.tickets.each_with_index do |ticket, index| %>
    <tr class="<%= cycle('even', 'uneven') -%>">
      <td>
        <%= ticket.name %>
      </td>
      <td class="right"><%= nice_price ticket.price %></td>
      <td>
        <span class="button_delete">
          <%= link_to(
                'Delete',
                remove_ticket_from_cart_path(:position => index),
                :method => :delete,
                :remote => true
              ) %>
        </span>
        <%# if ticket.member and ticket.member.comment %>
          <%#=h ticket.member.comment %>
        <%# end %>
      </td>
    </tr>
    <% end %>
    <tr>
      <td colspan="3" class="divider"></td>
    </tr>
    <tr>
      <td colspan="1"><h1>Total:</h1></td>
      <td colspan="2"><h1><%= nice_price @cart.total_price %></h1></td>
    </tr>
    <tr>
      <td colspan="3" id="checkout">
        <% unless params[:action] == "checkout" %>
          <%= link_to 'Checkout!', checkout_cart_path %>
        <% end %>
      </td>
    </tr>
  </table>
</div>

app/views/carts/_last_transaction.html.erb
<h1>Cancel Transaction: <%= @last_transaction.id %></h1>

<table class="overview">
  <thead>
    <tr>
      <th>ID</th>
      <th>Workshift</th>
      <th>Angel</th>
      <th>Time</th>
      <th>Valid</th>
      <th>Tickets</th>
      <th class="total">Total</th>
    </tr>
  </thead>
  <tbody>
  <%= render :partial => "transactions/transaction", :locals => {:transaction => @last_transaction} %>
  <tr>
    <td colspan="7" class="right"><strong>Sum: <%= nice_price @last_transaction.total %></strong></td>
  </tr>
  </tbody>
</table>

app/views/carts/cancel_most_recent.html.erb
<%= render :partial => "last_transaction" %>

<% form_tag confirm_cancel_cart_path do -%>
<p><%= label_tag 'login' %><br />
<%= text_field_tag 'login', @login %></p>

<p><%= label_tag 'password' %><br/>
<%= password_field_tag 'password', nil %></p>
<%= hidden_field_tag :transaction_id, @last_transaction.id %>
<p><%= submit_tag %></p>
<% end %>

app/views/carts/checkout.html.erb
<% if @bons %>
<div style="font-size: 300%">
  <h3><%= pluralize @bons.count, 'Belegnummer', 'Belegnummern' %></h3>
  <ul id="voucher_numbers">
    <% @bons.each do |bon| %>
      <li><%= bon.id %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= render :partial => 'cart' %>
<%= wait_for_close_with_button('index') %>

app/views/carts/confirm_cancel.html.erb
<h1>Cancelation successful - Return Money and destoy bill</h1>

<%= render :partial => "last_transaction" %>

<%= wait_for_close_with_button('index') %>

app/views/carts/show.html.erb
<div id="ticket_selection">
  <h1>Tickets</h1>
  <table id="tickets">
    <% Ticket.standard.available.each do |ticket| %>
    <% if ticket.name =~ /(^friends_|frei$)/ then next end %>
    <tr>
      <td>
        <div class="ticket_badge">
        <%= link_to(
              ticket.name,
              add_ticket_to_cart_path(:id => ticket.id),
              :method => :put,
              :remote => true
        ) %>
      </div>
      </td>
      <td class="price"><%= nice_price ticket.price %></td>
    </tr>
    <% end %>
  </table>
</div>

<div id="main_special_guest_search">

  <h4>Search</h4>
  <%= text_field_tag :search_term %>

  <script>
    live_search.init( '#search_term')
  </script>
  <div id="search_results"></div>
</div>


<%= render :partial => 'cart' %>

<div id="open_cashbox">
    <%= link_to "Open cashbox", open_cashbox_cart_path %>
</div>